version: '3'

networks:
  monitoring:
    driver: bridge

services:
  josh-node-1:
    container_name: "josh-node-1"    
    user: 0:0
    restart: unless-stopped
    build: 
      context: ..
      dockerfile: ./RaftDistributed/RaftNode/Dockerfile  
    environment:
      SERVER_NAME: "1"
      LIST_OF_NODES: "josh-node-1,josh-node-2,josh-node-3"
    ports:
      - "2320:8080"
    networks:
      - monitoring

  gateway:
    container_name: "josh-gateway"    
    user: 0:0
    restart: unless-stopped
    build: 
      context: ..
      dockerfile: ./RaftDistributed/GateWay/Dockerfile  
    environment:
      LIST_OF_NODES: "josh-node-1,josh-node-2,josh-node-3"
    ports:
      - "2319:8080"
    networks:
      - monitoring
