version: '3'

networks:
  monitoring:
    driver: bridge

services:
  josh-node-1:
    container_name: "josh-node-1"    
    user: 0:0
    restart: unless-stopped
    build: 
      context: ..
      dockerfile: /RaftDistributed/RaftNode/Dockerfile  
    environment:
      SERVER_NAME: "1"
      LIST_OF_NODES: "1=http://josh-node-1:8080;2=http://josh-node-2:8080;3=http://josh-node-3:8080;"
    volumes:
      - ${PWD}/RaftDistributed/information1/1LeaderInformation.txt:/app/1LeaderInformation.txt
      - ${PWD}/RaftDistributed/information1/1InfoStorage.txt:/app/1Info.txt

    ports:
      - "2320:8080"
    networks:
      - monitoring

  josh-node-2:
    container_name: "josh-node-2"    
    user: 0:0
    restart: unless-stopped
    build: 
      context: ..
      dockerfile: /RaftDistributed/RaftNode/Dockerfile  
    environment:
      SERVER_NAME: "2"
      LIST_OF_NODES: "1=http://josh-node-1:8080;2=http://josh-node-2:8080;3=http://josh-node-3:8080;"
    volumes:
      - /RaftDistributed/information2/2LeaderInformation.txt:/information/2LeaderInformation.txt
      - /RaftDistributed/information2/2InfoStorage.txt:/app/2Info.txt


    ports:
      - "2321:8080"
    networks:
      - monitoring

  josh-node-3:
    container_name: "josh-node-3"    
    user: 0:0
    restart: unless-stopped
    build: 
      context: ..
      dockerfile: /RaftDistributed/RaftNode/Dockerfile  
    environment:
      SERVER_NAME: "3"
      LIST_OF_NODES: "1=http://josh-node-1:8080;2=http://josh-node-2:8080;3=http://josh-node-3:8080;"
    volumes:
      - /RaftDistributed/information3/3LeaderInformation.txt:/information/3LeaderInformation.txt
      - /RaftDistributed/information3/3InfoStorage.txt:/app/3Info.txt
    ports:
      - "2322:8080"
    networks:
      - monitoring

  gateway:
    container_name: "josh-gateway"    
    user: 0:0
    restart: unless-stopped
    build: 
      context: ..
      dockerfile: /RaftDistributed/GateWay/Dockerfile  
    environment:
      LIST_OF_NODES: "1=http://josh-node-1:8080;2=http://josh-node-2:8080;3=http://josh-node-3:8080;"
    ports:
      - "2319:8080"
    networks:
      - monitoring
