version: '3'

networks:
  monitoring:
    driver: bridge

services:
  josh-node-1:
    container_name: "josh-node-1"    
    user: 0:0
    restart: unless-stopped
    build: 
      context: ..
      dockerfile: /RaftDistributed/RaftNode/Dockerfile  
    environment:
      SERVER_NAME: "1"
      LIST_OF_NODES: "1=http://josh-node-1:8080;2=http://josh-node-2:8080;3=http://josh-node-3:8080;"
    volumes:
      - /RaftDistributed/information1/:/app/information
      # - /RaftDistributed/information1/1LeaderInformation.txt:/app/1LeaderInformation.txt

    ports:
      - "2320:8080"
    networks:
      - monitoring

  josh-node-2:
    container_name: "josh-node-2"    
    user: 0:0
    restart: unless-stopped
    build: 
      context: ..
      dockerfile: /RaftDistributed/RaftNode/Dockerfile  
    environment:
      SERVER_NAME: "2"
      LIST_OF_NODES: "1=http://josh-node-1:8080;2=http://josh-node-2:8080;3=http://josh-node-3:8080;"
    volumes:
      - /RaftDistributed/information2/:/app/information


    ports:
      - "2321:8080"
    networks:
      - monitoring

  josh-node-3:
    container_name: "josh-node-3"    
    user: 0:0
    restart: unless-stopped
    build: 
      context: ..
      dockerfile: /RaftDistributed/RaftNode/Dockerfile  
    environment:
      SERVER_NAME: "3"
      LIST_OF_NODES: "1=http://josh-node-1:8080;2=http://josh-node-2:8080;3=http://josh-node-3:8080;"
    volumes:
      - /RaftDistributed/information3/:/app/information
    ports:
      - "2322:8080"
    networks:
      - monitoring

  gateway:
    container_name: "josh-gateway"    
    user: 0:0
    restart: unless-stopped
    build: 
      context: ..
      dockerfile: /RaftDistributed/GateWay/Dockerfile  
    environment:
      LIST_OF_NODES: "1=http://josh-node-1:8080;2=http://josh-node-2:8080;3=http://josh-node-3:8080;"
    ports:
      - "2319:8080"
    networks:
      - monitoring

  frontend:
    container_name: "josh-frontend"    
    user: 0:0
    # restart: unless-stopped
    build: 
      context: ..
      dockerfile: /RaftDistributed/FrontEndRaft/Dockerfile  
    environment:
      GATEWAY_URL_ARG: "http://josh-gateway:8080"
    ports:
      - "2323:8080"
    networks:
      - monitoring
