version: '3'

services:

  josh-node-3:
    container_name: "josh-node-3"    
    user: 0:0
    restart: unless-stopped
    build: 
      context: ..
      dockerfile: RaftNode/production/Dockerfile  
    environment:
      SERVER_NAME: "3"
      LIST_OF_NODES: "1=http://144.17.92.12:2320;2=http://144.17.92.12:2321;"
    volumes:
      - ./information.txt:/app/3LeaderInformation.txt
      - ./information2.txt:/app/InfoStorage3.txt
    ports:
      - "2322:8080"