version: '3'

networks:
  monitoring:
    driver: bridge


volumes:
  grafana_storage: {}


services:
  josh-node-1:
    container_name: "josh-node-1"    
    user: 0:0
    restart: unless-stopped
    build: 
      context: ..
      dockerfile: RaftNode/production/Dockerfile    
    environment:
      SERVER_NAME: "1"
      LIST_OF_NODES: "2=http://josh-node-2:8080;3=http://144.17.92.13:2322"
    ports:
      - "2320:8080"
    volumes:
      - ./information.txt:/1LeaderInformation.txt
      - ./information2.txt:/InfoStorage1.txt

    networks:
      - monitoring

  josh-node-2:
    container_name: "josh-node-2"    
    user: 0:0
    restart: unless-stopped
    build: 
      context: ..
      dockerfile: RaftNode/production/Dockerfile   
    environment:
      SERVER_NAME: "2"
      LIST_OF_NODES: "1=http://josh-node-1:8080;3=http://144.17.92.13:2322"
    volumes:
      - ./information3.txt:/app/2LeaderInformation.txt
      - ./information4.txt:/app/InfoStorage2.txt
    ports:
      - "2321:8080"
    networks:
      - monitoring
       
  gateway:
    container_name: "josh-gateway"    
    user: 0:0
    restart: unless-stopped
    build: 
      context: ..
      dockerfile: GateWay/production/Dockerfile  
    environment:
      LIST_OF_NODES: "1=http://josh-node-1:8080;2=http://josh-node-2:8080;3=http://144.17.92.13:2322"
    ports:
      - "2319:8080"
    networks:
      - monitoring
  
  frontend:
    container_name: "josh-frontend"    
    user: 0:0
    restart: unless-stopped
    build: 
      context: ..
      dockerfile: RaftFrontEnd/production/Dockerfile  
    ports:
      - "2323:8080"
    networks:
      - monitoring

  josh-otel-collector:
    container_name: "josh-otel-collector"
    image: otel/opentelemetry-collector-contrib
    restart: unless-stopped
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1369:1888 # pprof extension
      - 1370:8888 # Prometheus metrics exposed by the Collector
      - 1371:8889 # Prometheus exporter metrics
      - 1372:13133 # health_check extension
      - 1373:4317 # OTLP gRPC receiver
      - 1374:4318 # OTLP http receiver
      - 1375:55679 # zpages extension
    networks:
      - monitoring

  josh-node-exporter:
    container_name: "josh-node-exporter"
    image: prom/node-exporter:latest
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "1376:9100"
    networks:
      - monitoring

  josh-grafana:
    container_name: "josh-grafana"
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "1379:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=josh
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    depends_on:
      - josh-loki
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      - monitoring

  josh-loki:
    container_name: "josh-loki"
    image: grafana/loki:latest    
    restart: unless-stopped
    ports: 
      - "1380:3100"
    command: -config.file=/etc/loki-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki-config.yaml
    networks:
      - monitoring