@RaftNode_HostAddress = http://localhost:2320

GET {{RaftNode_HostAddress}}/Node/GetOtherId/2
Accept: application/json

###
#Next steps:
# 1. In node:
   
# 2. In gateway:
# 3 In both:
    # figure out all relevant functions that may be called
    # make skeleton functions for all of them
# 4 Outside both:
    #Look at rubric
    # Add prometheus/grafana stuff
    # etc